plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    // FFT (optional for later)

    // SQLite
    implementation "org.xerial:sqlite-jdbc:3.46.1.0"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'soundwave.Main'
}
